---
- name: verify download destination exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/env_setup/dotnet"
    state: directory

- name: download msft signing key and repo
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/config/ubuntu/{{ ubuntu_version }}/packages-microsoft-prod.deb"
    dest: "{{ ansible_user_dir }}/env_setup/dotnet/packages-microsoft-prod.deb"
    mode: "0700"

- name: install msft signing key and repo
  ansible.builtin.shell:
    cmd: "dpkg -i {{ ansible_user_dir }}/env_setup/dotnet/packages-microsoft-prod.deb"
  become: true

- name: install dotnet
  ansible.builtin.package:
    name:
      - dotnet-sdk-7.0
  become: true
