---
- name: install
  ansible.builtin.shell:
    cmd: brew install derailed/k9s/k9s

- name: directory
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/k9s"
    state: directory

- name: skin.yml
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/k9s/skin.yml"
    src: "skin.yml"
