---
- name: verify download destination exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/env_setup/lazygit"
    state: directory

- name: download metadata
  ansible.builtin.get_url:
    url: "https://api.github.com/repos/jesseduffield/lazygit/releases/latest"
    dest: "{{ ansible_user_dir }}/env_setup/lazygit/metadata"
    mode: "0700"

- name: get tag
  ansible.builtin.shell:
    cmd: "cat {{ ansible_user_dir }}/env_setup/lazygit/metadata | grep -Po '\"tag_name\":\"v\\K[^\"]*'"
  register: lazygit_ver

- name: download release
  ansible.builtin.get_url:
    url: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_ver.stdout }}_Linux_x86_64.tar.gz"
    dest: "{{ ansible_user_dir }}/env_setup/lazygit/lazygit.tar.gz"
    mode: "0700"

- name: extract release
  ansible.builtin.unarchive:
    src: "{{ ansible_user_dir }}/env_setup/lazygit/lazygit.tar.gz"
    dest: "{{ ansible_user_dir }}/env_setup/lazygit"

- name: install
  ansible.builtin.shell:
    cmd: "install {{ ansible_user_dir }}/env_setup/lazygit/lazygit /usr/local/bin"
  become: true

