---
- name: verify download destination exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/env_setup/nodejs"
    state: directory

- name: download setup script
  ansible.builtin.get_url:
    url: "https://deb.nodesource.com/setup_20.x"
    dest: "{{ ansible_user_dir }}/env_setup/nodejs/setup_20.x"
    mode: "0700"

- name: run setup script
  ansible.builtin.shell: "{{ ansible_user_dir }}/env_setup/nodejs/setup_20.x"
  become: true

- name: install
  ansible.builtin.package:
    name:
      - nodejs
      - make
      - gcc
      - g++
  become: true
