---
- name: verify download destination exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/env_setup/kubectl"
    state: directory

- name: download gpg key
  ansible.builtin.get_url:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    dest: "{{ ansible_user_dir }}/env_setup/kubectl/apt-key.gpg"
    mode: "0700"

- name: add the gpg key
  ansible.builtin.shell:
    cmd: "gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg {{ ansible_user_dir }}/env_setup/kubectl/apt-key.gpg"
  become: true

- name: add the apt repo
  ansible.builtin.shell:
    cmd: "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main' | tee /etc/apt/sources.list.d/kubernetes.list"
  become: true

- name: update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: install
  ansible.builtin.package:
    name:
      - kubectl
    state: latest
  become: true
