---
- name: install
  ansible.builtin.package:
    name:
      - i3
    state: latest
  become: true

- name: clone themer
  ansible.builtin.git:
    clone: true
    depth: 1
    dest: "{{ ansible_user_dir }}/env_setup/i3wm-themer"
    repo: https://github.com/unix121/i3wm-themer
    update: true
    version: main

- name: copy i3 config default
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/env_setp/i3wm-themer/defaults/i3.template"
    src: "i3_config.j2"
    force: true

- name: pip install
  ansible.builtin.shell:
    cmd: "pip install pyyaml"
  become: true

- name: install deps
  ansible.builtin.shell:
    cmd: "echo 'Y' | {{ ansible_user_dir }}/env_setup/i3wm-themer/install_ubuntu.sh"
  become: true

- name: copy tool config
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/env_setup/i3wm-themer/config.yaml"
    src: "themer_config.j2"
    force: true

- name: create polybar config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/polybar"
    state: directory

- name: create nitrogen config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nitrogen"
    state: directory

- name: touch i3 config
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/i3/config"
    state: touch
    mode: "0644"

- name: touch xresources
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.Xresources"
    state: touch
    mode: "0644"

- name: touch nitrogen config
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nitrogen/bg-saved.cfg"
    state: touch
    mode: "0644"

- name: touch polybar config
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/polybar/config"
    state: touch
    mode: "0644"

- name: copy polybar configs
  ansible.builtin.shell:
    cmd: "cp -r {{ ansible_user_dir }}/env_setup/i3wm-themer/scripts/* /home/$USER/.config/polybar/"

- name: install defaults
  ansible.builtin.shell:
    cmd: "python3 {{ ansible_user_dir }}/env_setup/i3wm-themer/i3wm-themer.py --config {{ ansible_user_dir }}/env_setup/i3wm-themer/config.yaml --install {{ ansible_user_dir }}/env_setup/i3wm-themer/defaults/"

- name: apply theme
  ansible.builtin.shell:
    cmd: "python3 {{ ansible_user_dir }}/env_setup/i3wm-themer/i3wm-themer.py --config {{ ansible_user_dir }}/env_setup/i3wm-themer/config.yaml --load {{ ansible_user_dir }}/env_setup/i3wm-themer/themes/013.json"
