---
- name: prerequisites
  ansible.builtin.package:
    name:
      - fuse2
      - libxi
      - libxrender
      - libxtst
      - mesa-utils
      - fontconfig
      - gtk3
      - dbus
    state: latest
  become: true

- name: download file
  ansible.builtin.get_url:
    url: "https://download.jetbrains.com/product?code=TB&latest&distribution=linux"
    dest: "/tmp/toolbox.tar.gz"
    mode: "0755"
  become: true

- name: make directory in opt
  ansible.builtin.file:
    path: "/opt/jetbrains-toolbox"
    state: "directory"
  become: true

- name: unpack
  ansible.builtin.shell: "tar -xzf /tmp/toolbox.tar.gz --strip-components=1 -C /opt/jetbrains-toolbox"
  become: true
